cd /home/ubuntu/flask-sqlite-app || exit 1

echo "Syncing develop branch..."
git fetch origin develop
git reset --hard origin/develop

echo "Updating STAGING containers..."
ENV_FILE=.env.staging docker compose down
ENV_FILE=.env.staging docker compose \
  -f docker-compose.yml \
  -f docker-compose.staging.yml \
  up -d --build
